language: php

php:
  - 5.6.4
  - 7.0

env:
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite
  APP_KEY: 16efa6c23c2e8c705826b0e66778fbe7
  JWT_SECRET: ki8jSvMf5wFrlSRBAWcGbmAzBUJfc8p8
  ADMIN_EMAIL: koel@example.com
  ADMIN_NAME: Koel
  ADMIN_PASSWORD: SoSecureK0el
  LASTFM_API_KEY: foo
  LASTFM_API_SECRET: bar
  BROADCAST_DRIVER: log

branches:
  - master

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - phpunit
  - npm test
