language: php

#addons:
#  chrome: stable

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

#node_js:
#  - 10

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction
#  - cd resources/assets && yarn
#  - cd ../.. && yarn && yarn production

script:
  # Backend
  - composer coverage
#  # Cypress
#  - yarn cy

cache:
  directories:
    - vendor/

addons:
  code_climate:
    repo_token: e74dc85a4eeb025a067bde238175f44d9f6a9e544278c4c096a46b8467c5fb9f
  apt:
    packages:
    - libgconf-2-4

after_success:
  - vendor/bin/test-reporter
  - bash <(curl -s https://codecov.io/bash)
